(window.webpackJsonp=window.webpackJsonp||[]).push([[40],{491:function(e,t,s){"use strict";s.r(t);var a=s(2),r=Object(a.a)({},(function(){var e=this,t=e.$createElement,s=e._self._c||t;return s("ContentSlotsDistributor",{attrs:{"slot-key":e.$parent.slotKey}},[s("h1",{attrs:{id:"day-2-w4-api-promises"}},[s("a",{staticClass:"header-anchor",attrs:{href:"#day-2-w4-api-promises"}},[e._v("#")]),e._v(" Day 2 - W4 API/Promises")]),e._v(" "),s("h3",{attrs:{id:"daily-project-https-github-com-loganponder-spring21-gregslist-mvc"}},[s("a",{staticClass:"header-anchor",attrs:{href:"#daily-project-https-github-com-loganponder-spring21-gregslist-mvc"}},[e._v("#")]),e._v(" Daily Project: https://github.com/LoganPonder/spring21-gregslist-mvc")]),e._v(" "),s("h3",{attrs:{id:"what-are-the-three-states-of-a-promise"}},[s("a",{staticClass:"header-anchor",attrs:{href:"#what-are-the-three-states-of-a-promise"}},[e._v("#")]),e._v(" What are the three states of a Promise?")]),e._v(" "),s("p",[s("strong",[e._v("Pending:")]),e._v(" Initial State, before the Promise succeeds or fails")]),e._v(" "),s("p",[s("strong",[e._v("Resolved:")]),e._v(" Completed Promise")]),e._v(" "),s("p",[s("strong",[e._v("Rejected:")]),e._v(" Failed Promise")]),e._v(" "),s("h3",{attrs:{id:"how-do-promises-seek-to-resolve-the-issues-of-callback-hell"}},[s("a",{staticClass:"header-anchor",attrs:{href:"#how-do-promises-seek-to-resolve-the-issues-of-callback-hell"}},[e._v("#")]),e._v(' How do promises seek to resolve the issues of "callback hell"?')]),e._v(" "),s("p",[e._v("Promises allow for a cleaner syntax, allowing us to chain them together as opposed to continually passing callbacks as arguments for eachother.")]),e._v(" "),s("h3",{attrs:{id:"what-is-the-difference-between-then-and-catch"}},[s("a",{staticClass:"header-anchor",attrs:{href:"#what-is-the-difference-between-then-and-catch"}},[e._v("#")]),e._v(" What is the difference between .then() and .catch()?")]),e._v(" "),s("p",[e._v(".then() runs when a promis returns successfull. .then() will execute when some type of condition is met.... .catch() runs when there is some sort of error.")])])}),[],!1,null,null,null);t.default=r.exports}}]);